/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view.consulta;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.controller.FilmeController;
import locadora.model.Filme;

/**
 *
 * @author regis
 */
public class ConsultaFilme extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsulta
     */
    Filme filme;

    public ConsultaFilme() {
        initComponents();
        mostrarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelFilme = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPesquisaFilme = new javax.swing.JTextField();
        jButtonBuscarFilme = new javax.swing.JButton();
        jTextFieldCodFilme = new javax.swing.JTextField();
        jTextFieldMidia = new javax.swing.JTextField();
        jTextFieldGeneroFilme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSinopseFilme = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFilmes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDuracao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTituloFilme = new javax.swing.JTextField();
        jTextFieldAtor = new javax.swing.JTextField();
        jFormattedTextFieldPreco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Consulta");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Locadora Sessão das Dez - Consulta Filme");

        jPanelFilme.setBackground(new java.awt.Color(51, 51, 51));
        jPanelFilme.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Pesquisa por filme");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Título:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genêro:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sinopse:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duracão:");

        jTextFieldPesquisaFilme.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisaFilme.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldPesquisaFilme.setForeground(new java.awt.Color(0, 0, 0));

        jButtonBuscarFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButtonBuscarFilme.setAlignmentY(0.0F);
        jButtonBuscarFilme.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBuscarFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarFilme.setPreferredSize(new java.awt.Dimension(46, 32));
        jButtonBuscarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarFilmeActionPerformed(evt);
            }
        });

        jTextFieldCodFilme.setEditable(false);
        jTextFieldCodFilme.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodFilme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldCodFilme.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodFilmeActionPerformed(evt);
            }
        });

        jTextFieldMidia.setEditable(false);
        jTextFieldMidia.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMidia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldMidia.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldMidia.setText(" ");
        jTextFieldMidia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldMidia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMidiaActionPerformed(evt);
            }
        });

        jTextFieldGeneroFilme.setEditable(false);
        jTextFieldGeneroFilme.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldGeneroFilme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldGeneroFilme.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldGeneroFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGeneroFilmeActionPerformed(evt);
            }
        });

        jTextAreaSinopseFilme.setEditable(false);
        jTextAreaSinopseFilme.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaSinopseFilme.setColumns(18);
        jTextAreaSinopseFilme.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaSinopseFilme.setLineWrap(true);
        jTextAreaSinopseFilme.setRows(5);
        jTextAreaSinopseFilme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jScrollPane1.setViewportView(jTextAreaSinopseFilme);

        jTableFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Ator/Atriz", "Genêro", "Sinopse", "Duração", "Mìdia", "Preco"
            }
        ));
        jTableFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFilmesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFilmes);
        if (jTableFilmes.getColumnModel().getColumnCount() > 0) {
            jTableFilmes.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 241, 131));
        jLabel8.setText("Tabela Filmes ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes.png"))); // NOI18N

        jTextFieldDuracao.setEditable(false);
        jTextFieldDuracao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDuracao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldDuracao.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracaoActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Minutos");

        jButtonLimpar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(0, 0, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setEnabled(false);
        jButtonEditar.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(0, 0, 255));
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmar.setEnabled(false);
        jButtonConfirmar.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Preço:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mídia:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ator:");

        jTextFieldTituloFilme.setEditable(false);
        jTextFieldTituloFilme.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTituloFilme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldTituloFilme.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTituloFilme.setText(" ");
        jTextFieldTituloFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldTituloFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloFilmeActionPerformed(evt);
            }
        });

        jTextFieldAtor.setEditable(false);
        jTextFieldAtor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAtor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldAtor.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtorActionPerformed(evt);
            }
        });

        jFormattedTextFieldPreco.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldPreco.setForeground(new java.awt.Color(255, 0, 0));
        jFormattedTextFieldPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPreco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelFilmeLayout = new javax.swing.GroupLayout(jPanelFilme);
        jPanelFilme.setLayout(jPanelFilmeLayout);
        jPanelFilmeLayout.setHorizontalGroup(
            jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFilmeLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmeLayout.createSequentialGroup()
                                .addGap(0, 36, Short.MAX_VALUE)
                                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmeLayout.createSequentialGroup()
                                        .addComponent(jTextFieldCodFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addComponent(jTextFieldGeneroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                                        .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAtor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(271, 271, 271))))
        );
        jPanelFilmeLayout.setVerticalGroup(
            jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFilmeLayout.createSequentialGroup()
                                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmeLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMidia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonBuscarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPesquisaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextFieldCodFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(jTextFieldAtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGeneroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanelFilmeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jButtonLimpar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1073, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarFilmeActionPerformed
        FilmeController filmeController = new FilmeController();
//        filmeController.consultarFilme(jTextFieldPesquisaFilme.getText());

        Filme filmeE = filmeController.consultarFilme(jTextFieldPesquisaFilme.getText());
        if (filmeE != null) {
            try {
                jTextFieldCodFilme.setText(String.valueOf(filmeE.getCodFilme()));
                jTextFieldMidia.setText(filmeE.getTitulo());
                jTextFieldTituloFilme.setText(filmeE.getTitulo());
                jFormattedTextFieldPreco.setText(String.valueOf(filmeE.getPreco()));
                jTextFieldAtor.setText(filmeE.getAtor());
                jTextFieldGeneroFilme.setText(filmeE.getGenero());
                jTextAreaSinopseFilme.setText(filmeE.getSinopse());
                jTextFieldDuracao.setText(String.valueOf(filmeE.getDuracao()));

                // Habilita o botão Editar
                jButtonEditar.setEnabled(true);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "digite número no campo preço!"+e);
                return;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Filme não encontrado.");
            jTextFieldPesquisaFilme.setText("");
            jTextFieldCodFilme.setText("");
            jTextFieldMidia.setText("");
            jTextFieldGeneroFilme.setText("");
            jTextAreaSinopseFilme.setText("");
            jTextFieldDuracao.setText("");
        }
    }//GEN-LAST:event_jButtonBuscarFilmeActionPerformed

    private void jTextFieldCodFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodFilmeActionPerformed

    private void jTextFieldMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMidiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMidiaActionPerformed

    private void jTextFieldGeneroFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGeneroFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGeneroFilmeActionPerformed

    private void jTextFieldDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracaoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
        jTextFieldPesquisaFilme.setText("");
        jTextFieldCodFilme.setText("");
        jTextFieldMidia.setText("");
        jTextFieldGeneroFilme.setText("");
        jTextAreaSinopseFilme.setText("");
        jTextFieldDuracao.setText("");
        jTextFieldTituloFilme.setText("");
        jFormattedTextFieldPreco.setText("");
        jTextFieldAtor.setText("");

        // Desabilita os botões Editar e Confirmar
        jButtonEditar.setEnabled(false);
        jButtonConfirmar.setEnabled(false);

    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTableFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFilmesMouseClicked

        jTextFieldCodFilme.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 0).toString());
        jTextFieldTituloFilme.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 1).toString());
        jTextFieldAtor.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 2).toString());
        jTextFieldGeneroFilme.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 3).toString());
        jTextAreaSinopseFilme.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 4).toString());
        jTextFieldDuracao.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 5).toString());
        jTextFieldMidia.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 6).toString());
        jFormattedTextFieldPreco.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 7).toString());

        // Habilita o botão editar
        jButtonEditar.setEnabled(true);
    }//GEN-LAST:event_jTableFilmesMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Habilita o botão Confirmar
        jButtonConfirmar.setEnabled(true);
        jTextAreaSinopseFilme.setEditable(true);
        jTextFieldMidia.setEditable(true);
        jTextFieldGeneroFilme.setEditable(true);
        jTextFieldDuracao.setEditable(true);
        jTextFieldTituloFilme.setEditable(true);
        jTextFieldGeneroFilme.setEditable(true);
        jTextFieldMidia.setEditable(true);
        jTextFieldAtor.setEditable(true);
        jTextFieldTituloFilme.requestFocus(); // dá um focu(cursor) no campo título do filme

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        
        int codigo = 0;
        String titulo = null;
        String ator = null;
        String genero = null;
        String midia = null;
        double preco = 0;
        int duracao = 0;
        try {
            codigo = Integer.parseInt(jTextFieldCodFilme.getText());
            duracao = Integer.parseInt(jTextFieldDuracao.getText());
            preco = Double.parseDouble(jFormattedTextFieldPreco.getText().replace(",", "."));
            titulo = jTextFieldTituloFilme.getText();
            midia = jTextFieldMidia.getText();
            ator = jTextFieldAtor.getText();
            genero = jTextFieldGeneroFilme.getText();
            
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Digitar somente número em preço!");
            jFormattedTextFieldPreco.requestFocus();
            return;
        }
                
        if (codigo > 0) {
            
            Filme filme = new Filme(codigo, titulo, ator, genero, genero, midia, preco, duracao);
            FilmeController filmeController = new FilmeController();
            filmeController.editarFilme(filme);
 
            // Limpa todos os campos e desahilita os botões Editar e Confirmar
            jTextFieldPesquisaFilme.setText("");
            jTextFieldCodFilme.setText("");
            jTextFieldTituloFilme.setText("");
            jTextFieldAtor.setText("");
            jTextFieldGeneroFilme.setText("");
            jTextFieldMidia.setText("");
            jFormattedTextFieldPreco.setText("");
            jTextAreaSinopseFilme.setText("");
            jTextFieldDuracao.setText("");

            // Desabilita os botões Editar e Confirmar
            jButtonEditar.setEnabled(false);
            jButtonConfirmar.setEnabled(false);
            
            // Atualiza a Tabela
            DefaultTableModel atualizar = (DefaultTableModel) jTableFilmes.getModel();
            atualizar.setNumRows(0);
            mostrarTabela();
       }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jTextFieldTituloFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloFilmeActionPerformed

    private void jTextFieldAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFilme.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFilme.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFilme.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFilme.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarFilme;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelFilme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFilmes;
    private javax.swing.JTextArea jTextAreaSinopseFilme;
    private javax.swing.JTextField jTextFieldAtor;
    private javax.swing.JTextField jTextFieldCodFilme;
    private javax.swing.JTextField jTextFieldDuracao;
    private javax.swing.JTextField jTextFieldGeneroFilme;
    private javax.swing.JTextField jTextFieldMidia;
    private javax.swing.JTextField jTextFieldPesquisaFilme;
    private javax.swing.JTextField jTextFieldTituloFilme;
    // End of variables declaration//GEN-END:variables

    private void mostrarTabela() {

        DefaultTableModel tableModel = (DefaultTableModel) jTableFilmes.getModel();
        FilmeController filmes = new FilmeController();
        
        for (Filme filme : filmes.atualizarTabela()) {
            tableModel.addRow(new Object[]{
                filme.getCodFilme(),
                filme.getTitulo(),
                filme.getAtor(),
                filme.getGenero(),
                filme.getSinopse(),
                filme.getDuracao(),
                filme.getMidia(),
                filme.getPreco()
                    
            });

        }
    }

}
