/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.controller.AluguelController;
import locadora.controller.ClienteController;
import locadora.controller.FilmeController;
import locadora.model.Aluguel;
import locadora.model.Cliente;
import locadora.model.Filme;

/**
 *
 * @author regis
 */
public class TelaAlugar extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlugar
     */
    private Thread th;
    private boolean executaHora = true;
    private ClienteController clienteController;
    private FilmeController filmeController;
    private final double PRECO_FIXO = 4.5; // preço da locação de um filme
    private int qtd_filme = 0; // quantidade de filme que o cliente está alugando
    private double valorTotal = 0.0; // valor total da locação do cliente
    private Aluguel aluguel;
    boolean pagamentoDepois = false; // variavel que vai verificar o pagamento
    private AluguelController aluguelController;

    public TelaAlugar() {

        initComponents();
        clienteController = new ClienteController();
        filmeController = new FilmeController();
        pegaTela();
        horaStart();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConfirmarFilme = new javax.swing.JButton();
        jButtonLimparFilme = new javax.swing.JButton();
        jButtonLimparCliente = new javax.swing.JButton();
        jPanelDevolucao = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCodFilmeDevolucao = new javax.swing.JTextField();
        jButtonDevolverFilme = new javax.swing.JButton();
        jPanelDevolucaoFicha = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jFormattedDtDevolucao = new javax.swing.JFormattedTextField();
        jFormattedDevolucaoEntrega = new javax.swing.JFormattedTextField();
        jFormattedDevolucaoMulta = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldDevolucaoCliente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFilmesAlugado = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldPagou = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldCodAluguel = new javax.swing.JTextField();
        jButtonDevolucaoConfirma = new javax.swing.JButton();
        jButtonPagaNaHora = new javax.swing.JButton();
        jButtonDevolucaoLimpar = new javax.swing.JButton();
        jPanelPedido = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jFormattedDataLocacao = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextFieldValorTotal = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldValorTroco = new javax.swing.JFormattedTextField();
        jButtonCaixaLimpar = new javax.swing.JButton();
        jButtonCaixaConfirma = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldCodigoLocacao = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButtonMaisFilme = new javax.swing.JButton();
        jTextFieldCodigoClienteCaixa = new javax.swing.JTextField();
        jTextFieldPrecoFixoCaixa = new javax.swing.JTextField();
        jTextFieldCodigoFilmeCaixa = new javax.swing.JTextField();
        jTextFieldQtdFilmeCaixa = new javax.swing.JTextField();
        jFormattedTextFieldValorVista = new javax.swing.JFormattedTextField();
        jButtonSalvarBD = new javax.swing.JButton();
        dateChooserComboDtDevolucao = new datechooser.beans.DateChooserCombo();
        jButtonEncontrarCliente1 = new javax.swing.JButton();
        jButtonEncontrarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelFilme = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFilme = new javax.swing.JTable();
        jTextFieldAtor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodFilme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodCliente = new javax.swing.JTextField();
        jLabelFilme = new javax.swing.JLabel();
        jPanelCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jFormattedCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jButtonConsultaFilmes = new javax.swing.JButton();
        jButtonConsultaCliente = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelHora = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seja Bem-Vindo(a) - Locadora Sessão das Dez");
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonConfirmarFilme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonConfirmarFilme.setForeground(new java.awt.Color(0, 51, 51));
        jButtonConfirmarFilme.setText("Confirmar Filme");
        jButtonConfirmarFilme.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConfirmarFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmarFilme.setEnabled(false);
        jButtonConfirmarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarFilme);
        jButtonConfirmarFilme.setBounds(290, 550, 211, 23);

        jButtonLimparFilme.setText("Limpar");
        jButtonLimparFilme.setToolTipText("");
        jButtonLimparFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimparFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparFilme);
        jButtonLimparFilme.setBounds(400, 515, 100, 30);

        jButtonLimparCliente.setText("Limpar ");
        jButtonLimparCliente.setToolTipText("");
        jButtonLimparCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparCliente);
        jButtonLimparCliente.setBounds(390, 220, 100, 30);

        jPanelDevolucao.setBackground(new Color(255,204,102, 155));
        jPanelDevolucao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Devolução");

        jLabel17.setText("Código Cliente:");

        jButtonDevolverFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButtonDevolverFilme.setToolTipText("Verificar Entrega");
        jButtonDevolverFilme.setBorder(null);
        jButtonDevolverFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanelDevolucaoFicha.setBackground(new Color(204,181,134, 200)
        );
        jPanelDevolucaoFicha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Locação", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel20.setText("Data de Locação:");

        jLabel19.setText("Data de Entrega:");

        jLabel21.setText("Multa R$");

        jFormattedDtDevolucao.setEditable(false);
        jFormattedDtDevolucao.setForeground(new java.awt.Color(255, 51, 0));
        jFormattedDtDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jFormattedDevolucaoEntrega.setEditable(false);
        jFormattedDevolucaoEntrega.setForeground(new java.awt.Color(255, 51, 0));
        jFormattedDevolucaoEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jFormattedDevolucaoMulta.setEditable(false);
        jFormattedDevolucaoMulta.setForeground(new java.awt.Color(255, 0, 0));
        jFormattedDevolucaoMulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jLabel22.setText("Nome do Cliente:");

        jTextFieldDevolucaoCliente.setEditable(false);
        jTextFieldDevolucaoCliente.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDevolucaoCliente.setForeground(new java.awt.Color(0, 0, 0));

        jLabel23.setText("Filmes Alugados");

        jTableFilmesAlugado.setBackground(new java.awt.Color(255, 255, 153));
        jTableFilmesAlugado.setForeground(new java.awt.Color(51, 51, 51));
        jTableFilmesAlugado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableFilmesAlugado);

        jLabel24.setText("Código do Cliente:");

        jTextFieldCodigoCliente.setEditable(false);
        jTextFieldCodigoCliente.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCodigoCliente.setForeground(new java.awt.Color(0, 0, 0));

        jLabel25.setText("Pagou?");

        jTextFieldPagou.setEditable(false);
        jTextFieldPagou.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPagou.setForeground(new java.awt.Color(255, 0, 0));

        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("Código Locação:");

        jTextFieldCodAluguel.setEditable(false);
        jTextFieldCodAluguel.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCodAluguel.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanelDevolucaoFichaLayout = new javax.swing.GroupLayout(jPanelDevolucaoFicha);
        jPanelDevolucaoFicha.setLayout(jPanelDevolucaoFichaLayout);
        jPanelDevolucaoFichaLayout.setHorizontalGroup(
            jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDevolucaoFichaLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedDtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedDevolucaoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel23))
                    .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedDevolucaoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPagou, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDevolucaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                        .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDevolucaoFichaLayout.setVerticalGroup(
            jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDevolucaoFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jFormattedDtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedDevolucaoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jFormattedDevolucaoMulta)
                        .addComponent(jTextFieldPagou)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldDevolucaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDevolucaoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldCodAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonDevolucaoConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa-confirma.png"))); // NOI18N
        jButtonDevolucaoConfirma.setToolTipText("Confirmar Devolução");
        jButtonDevolucaoConfirma.setBorder(null);
        jButtonDevolucaoConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonPagaNaHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money.png"))); // NOI18N
        jButtonPagaNaHora.setToolTipText("Fazer Pagamento Agora");
        jButtonPagaNaHora.setBorder(null);
        jButtonPagaNaHora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonDevolucaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clear.png"))); // NOI18N
        jButtonDevolucaoLimpar.setToolTipText("Limpar Campos");
        jButtonDevolucaoLimpar.setBorder(null);
        jButtonDevolucaoLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelDevolucaoLayout = new javax.swing.GroupLayout(jPanelDevolucao);
        jPanelDevolucao.setLayout(jPanelDevolucaoLayout);
        jPanelDevolucaoLayout.setHorizontalGroup(
            jPanelDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDevolucaoLayout.createSequentialGroup()
                .addGroup(jPanelDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDevolucaoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelDevolucaoFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDevolucaoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonDevolucaoConfirma)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonDevolucaoLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPagaNaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanelDevolucaoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanelDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(jPanelDevolucaoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodFilmeDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDevolverFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelDevolucaoLayout.setVerticalGroup(
            jPanelDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDevolucaoLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(12, 12, 12)
                .addGroup(jPanelDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevolverFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodFilmeDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDevolucaoFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDevolucaoConfirma)
                    .addComponent(jButtonPagaNaHora)
                    .addComponent(jButtonDevolucaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDevolucao);
        jPanelDevolucao.setBounds(940, 180, 410, 520);

        jPanelPedido.setBackground(new Color(212,241,153, 155));
        jPanelPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelPedido.setForeground(new java.awt.Color(255, 255, 153));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Caixa");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Valor de Locação Fixo R$");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Código Cliente:");

        jFormattedDataLocacao.setEditable(false);
        jFormattedDataLocacao.setBackground(new java.awt.Color(204, 204, 204));
        jFormattedDataLocacao.setForeground(new java.awt.Color(255, 0, 0));
        jFormattedDataLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedDataLocacao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Data Devolução:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Qtd Filmes:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Valor Total R$");

        jFormattedTextFieldValorTotal.setEditable(false);
        jFormattedTextFieldValorTotal.setBackground(new java.awt.Color(153, 153, 153));
        jFormattedTextFieldValorTotal.setBorder(null);
        jFormattedTextFieldValorTotal.setForeground(new java.awt.Color(102, 0, 0));
        jFormattedTextFieldValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldValorTotal.setToolTipText("");
        jFormattedTextFieldValorTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("Pag. a Vista R$");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("Troco R$");

        jFormattedTextFieldValorTroco.setBackground(new java.awt.Color(153, 153, 153));
        jFormattedTextFieldValorTroco.setBorder(null);
        jFormattedTextFieldValorTroco.setForeground(new java.awt.Color(102, 0, 0));
        jFormattedTextFieldValorTroco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jFormattedTextFieldValorTroco.setToolTipText("");
        jFormattedTextFieldValorTroco.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jButtonCaixaLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clear.png"))); // NOI18N
        jButtonCaixaLimpar.setToolTipText("Limpar Campos");
        jButtonCaixaLimpar.setBorder(null);
        jButtonCaixaLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCaixaLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaLimparActionPerformed(evt);
            }
        });

        jButtonCaixaConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa-confirma.png"))); // NOI18N
        jButtonCaixaConfirma.setToolTipText("Confirma Locação");
        jButtonCaixaConfirma.setBorder(null);
        jButtonCaixaConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCaixaConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaConfirmaActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Código da Locação para Pagamento na Devolução:");

        jTextFieldCodigoLocacao.setEditable(false);
        jTextFieldCodigoLocacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoLocacao.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCodigoLocacao.setText(" ");

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 204));
        jLabel28.setText("Data Locação:");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 204));
        jLabel29.setText("Código Filme:");

        jButtonMaisFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus.png"))); // NOI18N
        jButtonMaisFilme.setToolTipText("Adicionar Outro Filme");
        jButtonMaisFilme.setBorder(null);
        jButtonMaisFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMaisFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisFilmeActionPerformed(evt);
            }
        });

        jTextFieldCodigoClienteCaixa.setEditable(false);
        jTextFieldCodigoClienteCaixa.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCodigoClienteCaixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldCodigoClienteCaixa.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldPrecoFixoCaixa.setEditable(false);
        jTextFieldPrecoFixoCaixa.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPrecoFixoCaixa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPrecoFixoCaixa.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldPrecoFixoCaixa.setText(String.format("%5.2f", PRECO_FIXO));

        jTextFieldCodigoFilmeCaixa.setEditable(false);
        jTextFieldCodigoFilmeCaixa.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCodigoFilmeCaixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldCodigoFilmeCaixa.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldQtdFilmeCaixa.setEditable(false);
        jTextFieldQtdFilmeCaixa.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldQtdFilmeCaixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldQtdFilmeCaixa.setForeground(new java.awt.Color(255, 0, 0));

        jFormattedTextFieldValorVista.setBackground(new java.awt.Color(153, 153, 153));
        jFormattedTextFieldValorVista.setForeground(new java.awt.Color(102, 0, 0));
        jFormattedTextFieldValorVista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldValorVista.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jButtonSalvarBD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSalvarBD.setForeground(new java.awt.Color(51, 0, 0));
        jButtonSalvarBD.setText("Salvar no Banco");
        jButtonSalvarBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarBDActionPerformed(evt);
            }
        });

        dateChooserComboDtDevolucao.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        javax.swing.GroupLayout jPanelPedidoLayout = new javax.swing.GroupLayout(jPanelPedido);
        jPanelPedido.setLayout(jPanelPedidoLayout);
        jPanelPedidoLayout.setHorizontalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addComponent(jButtonCaixaConfirma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCaixaLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18))
                            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldValorVista))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserComboDtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecoFixoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCodigoClienteCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCodigoFilmeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldQtdFilmeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMaisFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelPedidoLayout.setVerticalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecoFixoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldCodigoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                        .addComponent(dateChooserComboDtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCodigoClienteCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodigoFilmeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtdFilmeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonMaisFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldValorVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvarBD)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCaixaLimpar)
                            .addComponent(jButtonCaixaConfirma))
                        .addGap(16, 16, 16))))
        );

        getContentPane().add(jPanelPedido);
        jPanelPedido.setBounds(525, 180, 410, 520);

        jButtonEncontrarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButtonEncontrarCliente1.setToolTipText("Encontrar Filme");
        jButtonEncontrarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEncontrarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncontrarCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEncontrarCliente1);
        jButtonEncontrarCliente1.setBounds(290, 515, 100, 30);

        jButtonEncontrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButtonEncontrarCliente.setToolTipText("Encontrar Cliente");
        jButtonEncontrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEncontrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncontrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEncontrarCliente);
        jButtonEncontrarCliente.setBounds(390, 180, 100, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 444, 500, 10);

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldStatus.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldStatus);
        jTextFieldStatus.setBounds(363, 280, 110, 30);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Status:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 280, 40, 30);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*somente pelo código");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 460, 130, 16);

        jPanelFilme.setBackground(new java.awt.Color(255, 204, 102));
        jPanelFilme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "informações de filme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jTableFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Ator", "Gênero", "Mídia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFilmeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFilme);

        javax.swing.GroupLayout jPanelFilmeLayout = new javax.swing.GroupLayout(jPanelFilme);
        jPanelFilme.setLayout(jPanelFilmeLayout);
        jPanelFilmeLayout.setHorizontalGroup(
            jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanelFilmeLayout.setVerticalGroup(
            jPanelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFilme);
        jPanelFilme.setBounds(10, 590, 510, 110);

        jTextFieldAtor.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldAtor.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldAtor);
        jTextFieldAtor.setBounds(70, 513, 200, 30);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ator:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 520, 27, 20);

        jTextFieldTitulo.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldTitulo.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(240, 480, 270, 30);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Título:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 480, 34, 30);

        jTextFieldCodFilme.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldCodFilme.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldCodFilme);
        jTextFieldCodFilme.setBounds(70, 480, 120, 30);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Código:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 480, 50, 30);

        jTextFieldCodCliente.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldCodCliente.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldCodCliente);
        jTextFieldCodCliente.setBounds(60, 210, 70, 24);

        jLabelFilme.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelFilme.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFilme.setText("Informações do Filme");
        getContentPane().add(jLabelFilme);
        jLabelFilme.setBounds(170, 450, 190, 20);

        jPanelCliente.setBackground(new java.awt.Color(255, 255, 145));
        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "informações do cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jTableCliente.setBackground(new java.awt.Color(255, 204, 102));
        jTableCliente.setForeground(new java.awt.Color(0, 0, 0));
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Data Nasc.", "Endereço", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelCliente);
        jPanelCliente.setBounds(10, 310, 510, 130);

        jTextFieldNomeCliente.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldNomeCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNomeCliente.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldNomeCliente);
        jTextFieldNomeCliente.setBounds(60, 240, 300, 27);

        jFormattedCpf.setBackground(new java.awt.Color(255, 204, 102));
        jFormattedCpf.setForeground(new java.awt.Color(51, 51, 51));
        try {
            jFormattedCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCpf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jFormattedCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedCpf);
        jFormattedCpf.setBounds(60, 270, 160, 30);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("cpf:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(33, 276, 21, 20);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 243, 40, 20);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(11, 210, 50, 20);

        jLabelCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCliente.setText("Locação para Cliente");
        getContentPane().add(jLabelCliente);
        jLabelCliente.setBounds(180, 180, 190, 24);

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close.png"))); // NOI18N
        jButtonClose.setToolTipText("Fechar Sistema");
        jButtonClose.setBorder(null);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose);
        jButtonClose.setBounds(690, 60, 140, 100);

        jButtonConsultaFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes-tela-aluguel.png"))); // NOI18N
        jButtonConsultaFilmes.setToolTipText("Página de Consulta de Filmes");
        jButtonConsultaFilmes.setBorder(null);
        jButtonConsultaFilmes.setContentAreaFilled(false);
        jButtonConsultaFilmes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultaFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaFilmesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultaFilmes);
        jButtonConsultaFilmes.setBounds(550, 60, 140, 110);

        jButtonConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        jButtonConsultaCliente.setToolTipText("Página de Consulta de Clientes");
        jButtonConsultaCliente.setBorder(null);
        jButtonConsultaCliente.setContentAreaFilled(false);
        jButtonConsultaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultaCliente);
        jButtonConsultaCliente.setBounds(410, 50, 140, 120);

        jButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRelatorio.setToolTipText("Relatório");
        jButtonRelatorio.setBorder(null);
        jButtonRelatorio.setContentAreaFilled(false);
        jButtonRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorio);
        jButtonRelatorio.setBounds(280, 60, 140, 110);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo Cliente");
        jButtonNovo.setBorder(null);
        jButtonNovo.setContentAreaFilled(false);
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(130, 60, 140, 110);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta-voltar.png"))); // NOI18N
        jButtonVoltar.setToolTipText("Voltar");
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.setPreferredSize(new java.awt.Dimension(128, 124));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(0, 50, 120, 124);

        jLabelHora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabelHora);
        jLabelHora.setBounds(1150, 10, 200, 30);

        jLabelFundo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelFundo.setForeground(new java.awt.Color(0, 0, 255));
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAlugar.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 1368, 770);

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.executaHora = false;
    }//GEN-LAST:event_formWindowClosed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        // Limpa os campos do Caixa
        jTextFieldCodigoClienteCaixa.setText("");
        jTextFieldCodigoFilmeCaixa.setText("");
        jTextFieldQtdFilmeCaixa.setText("");
        jFormattedTextFieldValorTotal.setText("");
        jFormattedTextFieldValorVista.setText("");
        jFormattedTextFieldValorTroco.setText("");

        // Limpa os campos de Cliente
        jTextFieldCodCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedCpf.setText("");
        jTextFieldStatus.setText("");
        jTextFieldCodigoClienteCaixa.setText("");

        // Limpa os campos de Filme
        jTextFieldCodFilme.setText("");
        jTextFieldTitulo.setText("");
        jTextFieldAtor.setText("");
        jTextFieldCodigoFilmeCaixa.setText("");

        // Desabilita o botão salvar no banco de dados
        jButtonSalvarBD.setEnabled(false);

        // Limpa as tabelas
        DefaultTableModel limpaCliente = (DefaultTableModel) jTableCliente.getModel();
        limpaCliente.setNumRows(0); // limpa cliente
        DefaultTableModel limpaFilme = (DefaultTableModel) jTableFilme.getModel();
        limpaFilme.setNumRows(0); // limpa filme
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jButtonConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultaClienteActionPerformed

    private void jButtonConsultaFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaFilmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultaFilmesActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonEncontrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncontrarClienteActionPerformed

        int codigo = 0;
        String status;

        try {
            codigo = Integer.parseInt(jTextFieldCodCliente.getText());
            Cliente cliente;

            cliente = this.clienteController.buscaCliente(codigo);
            if (cliente != null) {
                jTextFieldNomeCliente.setText(cliente.getNome());
                jFormattedCpf.setText(cliente.getCpf());
                // seta o codigo do cliente na parte da Caixa
                jTextFieldCodigoClienteCaixa.setText(String.valueOf(codigo));

                try {
                    status = cliente.getStatus();
                    if (!status.equals("pendente")) {
                        jTextFieldStatus.setText(status);
                    }
                } catch (NullPointerException e) {
                    jTextFieldStatus.setText("pendente");
                }

                Object cli[] = {
                    codigo,
                    cliente.getNome(),
                    cliente.getCpf(),
                    cliente.getDtNascimento(),
                    cliente.getEndereco(),
                    cliente.getEmail()
                };

                DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();

                model.addRow(cli);

            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado cliente com o"
                        + " código informado.");
                jTextFieldCodCliente.setText("");
                jTextFieldNomeCliente.setText("");
                jFormattedCpf.setText("");
                jTextFieldStatus.setText("");
            }

        } catch (NumberFormatException numberFormatException) {
            jTextFieldCodCliente.setText("");
        }

        if (codigo > 0) {
        } else {
            JOptionPane.showMessageDialog(null, "digite o código do cliente");
        }
    }//GEN-LAST:event_jButtonEncontrarClienteActionPerformed

    private void jFormattedCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedCpfActionPerformed

    private void jButtonLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparClienteActionPerformed

        jTextFieldCodCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedCpf.setText("");
        jTextFieldStatus.setText("");
        jTextFieldCodigoClienteCaixa.setText("");

        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_jButtonLimparClienteActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        jTextFieldCodigoClienteCaixa.setText("");

        // jTextFieldCodCliente.setText(jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 0).toString());
        jTextFieldCodigoClienteCaixa.setText(jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonEncontrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncontrarCliente1ActionPerformed
        int codigo = 0;
        try {
            codigo = Integer.parseInt(jTextFieldCodFilme.getText());

        } catch (NumberFormatException e) {
            jTextFieldCodFilme.setText("");
        }

        if (codigo > 0) {
            Filme filme = filmeController.consultarFilme(codigo);

            if (filme != null) {
                jTextFieldTitulo.setText(filme.getTitulo());
                jTextFieldAtor.setText(filme.getAtor());
                // seta o codigo do filme no campo codigo do filme dentro do caixa
                jTextFieldCodigoFilmeCaixa.setText(String.valueOf(codigo));
                // ativa o botão de confirmar filme
                jButtonConfirmarFilme.setEnabled(true);

                // preenche a tabela
                DefaultTableModel model = (DefaultTableModel) jTableFilme.getModel();
                model.addRow(new Object[]{
                    filme.getCodFilme(),
                    filme.getTitulo(),
                    filme.getAtor(),
                    filme.getGenero(),
                    filme.getMidia()
                });

            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado filme com "
                        + "o código informado.");
                jTextFieldCodFilme.setText("");
                jTextFieldTitulo.setText("");
                jTextFieldAtor.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite um código.");
        }

    }//GEN-LAST:event_jButtonEncontrarCliente1ActionPerformed

    private void jButtonLimparFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparFilmeActionPerformed

        jTextFieldCodFilme.setText("");
        jTextFieldTitulo.setText("");
        jTextFieldAtor.setText("");
        jTextFieldCodigoFilmeCaixa.setText("");
        DefaultTableModel model = (DefaultTableModel) jTableFilme.getModel();
        model.setNumRows(0); // limpa a tabela filme
    }//GEN-LAST:event_jButtonLimparFilmeActionPerformed

     private void jButtonConfirmarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarFilmeActionPerformed

        this.qtd_filme++;
        this.valorTotal += PRECO_FIXO;

        jTextFieldQtdFilmeCaixa.setText(String.valueOf(this.qtd_filme));
        jTextFieldCodFilme.setText("");
        jTextFieldTitulo.setText("");
        jTextFieldAtor.setText("");
        jButtonConfirmarFilme.setEnabled(false);
        jFormattedTextFieldValorTotal.setText(String.valueOf(String.format("%5.2f", this.valorTotal)));
    }//GEN-LAST:event_jButtonConfirmarFilmeActionPerformed

    private void jButtonCaixaLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaLimparActionPerformed

        // Limpa os campos do Caixa
        jTextFieldCodigoClienteCaixa.setText("");
        jTextFieldCodigoFilmeCaixa.setText("");
        jTextFieldQtdFilmeCaixa.setText("");
        jFormattedTextFieldValorTotal.setText("");
        jFormattedTextFieldValorVista.setText("");
        jFormattedTextFieldValorTroco.setText("");

        // Limpa os campos de Cliente
        jTextFieldCodCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedCpf.setText("");
        jTextFieldStatus.setText("");
        jTextFieldCodigoClienteCaixa.setText("");

        // Limpa os campos de Filme
        jTextFieldCodFilme.setText("");
        jTextFieldTitulo.setText("");
        jTextFieldAtor.setText("");
        jTextFieldCodigoFilmeCaixa.setText("");

        // Desabilita o botão salvar no banco de dados
        jButtonSalvarBD.setEnabled(false);
    }//GEN-LAST:event_jButtonCaixaLimparActionPerformed

    private void jButtonMaisFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisFilmeActionPerformed

        if (!jTextFieldCodigoFilmeCaixa.getText().equals("")) {
            List filmesLocacao = null;
            try {
                aluguel = new Aluguel();
                filmesLocacao = new ArrayList();
                filmesLocacao.add(Integer.parseInt(jTextFieldCodigoFilmeCaixa.getText()));
            } catch (NumberFormatException numberFormatException) {
                return;
            }
            // adiciona o filme a lista de filmes do objeto Aluguel
            aluguel.setFilmes(filmesLocacao);

            for (Object lista : aluguel.getFilmes()) {
                System.out.println(lista);
            }
            // limpa os campos de buscar filmes
            jTextFieldCodFilme.setText("");
            jTextFieldCodigoFilmeCaixa.setText("");
            jTextFieldTitulo.setText("");
            jTextFieldAtor.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Escolha um Filme!");
        }

        // limpa o campo do código do filme da Caixa
        jTextFieldCodigoFilmeCaixa.setText("");

        // dá um focu no campo de código filme na parte de buscar filme
        jTextFieldCodFilme.requestFocus();
    }//GEN-LAST:event_jButtonMaisFilmeActionPerformed

    private void jButtonCaixaConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaConfirmaActionPerformed

        if ((jTextFieldCodigoClienteCaixa.getText().equals("")) && (jTextFieldCodigoFilmeCaixa.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Necessário um cliente e pelo menos um Filme para realizar Locação.");
            return;
        }
        try {
            if ((!jFormattedTextFieldValorTotal.getText().equals(""))
                    && (!jFormattedTextFieldValorVista.getText().equals(""))) {

                double total = Double.parseDouble(jFormattedTextFieldValorTotal.getText().replace(",", "."));
                double pagVista = Double.parseDouble(jFormattedTextFieldValorVista.getText().replace(",", "."));
                double troco = pagVista - total;
                // seta o valor no campo troco do Caixa
                jFormattedTextFieldValorTroco.setText(String.valueOf(String.format("%5.2f", troco)).replace(".", ","));

                // habilita o botão salvar no banco
                jButtonSalvarBD.setEnabled(true);
            } else {
                if (jFormattedTextFieldValorVista.getText().equals("")) {

                    int pagou = JOptionPane.showConfirmDialog(null, "O cliente pagará na Entrega do Filme?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (pagou == JOptionPane.YES_OPTION) {
                        JOptionPane.showMessageDialog(null, "OK");
                        pagamentoDepois = true;

                    } else {
                        JOptionPane.showMessageDialog(null, "Coloque um valor para pagamento.");
                        jFormattedTextFieldValorVista.requestFocus();
                        jTextFieldQtdFilmeCaixa.setText("1");
                        jFormattedTextFieldValorTotal.setText("4.50");

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Campos para locação devem estar todos"
                            + " preenchidos!");
                    return;
                }
            }
        } catch (NumberFormatException numberFormatException) {
            return;
        } catch (HeadlessException headlessException) {
            return;
        }
    }//GEN-LAST:event_jButtonCaixaConfirmaActionPerformed

    private void jButtonSalvarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarBDActionPerformed
        // converter data para o tipo de Banco de Dados MySQL
        java.sql.Date dataLocacaoSQl;
        java.sql.Date dataEntregaSQl;

        dataLocacaoSQl = formatadorData(jFormattedDataLocacao.getText()); // dtLocação
        dataEntregaSQl = formatadorData(dateChooserComboDtDevolucao.getText()); // dtEntrega

        if ((!jTextFieldCodigoClienteCaixa.getText().equals(""))
                && (!jTextFieldCodigoFilmeCaixa.getText().equals(""))
                && (!jTextFieldQtdFilmeCaixa.getText().equals(""))) {

            Aluguel aluguel = new Aluguel();
            aluguel.setCodCliente(Integer.parseInt(jTextFieldCodigoClienteCaixa.getText()));
            aluguel.setDtAlugado(dataLocacaoSQl);
            aluguel.setDtDevolucao(dataLocacaoSQl);
            aluguel.setQuantidade(Integer.parseInt(jTextFieldQtdFilmeCaixa.getText()));
            aluguel.setPreco(Double.parseDouble(jFormattedTextFieldValorTotal.getText().replace(",", ".")));
            aluguel.setMulta(0.0);
            if (pagamentoDepois) {
                aluguel.setPagou("não");
            } else {
                aluguel.setPagou("sim");
            }
            // manda para o controller o objeto Aluguel
            this.aluguelController = new AluguelController();
            this.aluguelController.save(aluguel);

            // Limpa os Campos
            jTextFieldCodigoClienteCaixa.setText("");
            jTextFieldCodigoFilmeCaixa.setText("");
            jTextFieldQtdFilmeCaixa.setText("");
            jFormattedTextFieldValorTotal.setText("");
            jFormattedTextFieldValorVista.setText("");
            jFormattedTextFieldValorTroco.setText("");
            
            // Desabilita o botão salvar no banco
            jButtonSalvarBD.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "para salvar no bando de dados todos "
                    + "o campos devem ser preenchidos:\n"
                    + "Código Cliente:\n"
                    + "Código Filme:\n"
                    + "Qtd Filme:");

        }
    }//GEN-LAST:event_jButtonSalvarBDActionPerformed

    private void jTableFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFilmeMouseClicked

        jTextFieldCodigoFilmeCaixa.setText(jTableFilme.getValueAt(jTableFilme.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_jTableFilmeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlugar().setVisible(true);
            }
        });
    }

    private void pegaTela() {

        Toolkit tela = Toolkit.getDefaultToolkit();
        Dimension tamanho = tela.getScreenSize();
        int larg = (int) tamanho.getWidth();
        int alt = (int) tamanho.getHeight();
        this.setSize(larg, alt);
        this.setLocationRelativeTo(null);
//        setPreferredSize(tamanho);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserComboDtDevolucao;
    private javax.swing.JButton jButtonCaixaConfirma;
    private javax.swing.JButton jButtonCaixaLimpar;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConfirmarFilme;
    private javax.swing.JButton jButtonConsultaCliente;
    private javax.swing.JButton jButtonConsultaFilmes;
    private javax.swing.JButton jButtonDevolucaoConfirma;
    private javax.swing.JButton jButtonDevolucaoLimpar;
    private javax.swing.JButton jButtonDevolverFilme;
    private javax.swing.JButton jButtonEncontrarCliente;
    private javax.swing.JButton jButtonEncontrarCliente1;
    private javax.swing.JButton jButtonLimparCliente;
    private javax.swing.JButton jButtonLimparFilme;
    private javax.swing.JButton jButtonMaisFilme;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPagaNaHora;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonSalvarBD;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JFormattedTextField jFormattedCpf;
    private javax.swing.JFormattedTextField jFormattedDataLocacao;
    private javax.swing.JFormattedTextField jFormattedDevolucaoEntrega;
    private javax.swing.JFormattedTextField jFormattedDevolucaoMulta;
    private javax.swing.JFormattedTextField jFormattedDtDevolucao;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorTotal;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorTroco;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorVista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelFilme;
    private javax.swing.JLabel jLabelFundo;
    public javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelDevolucao;
    private javax.swing.JPanel jPanelDevolucaoFicha;
    private javax.swing.JPanel jPanelFilme;
    private javax.swing.JPanel jPanelPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableFilme;
    private javax.swing.JTable jTableFilmesAlugado;
    private javax.swing.JTextField jTextFieldAtor;
    private javax.swing.JTextField jTextFieldCodAluguel;
    private javax.swing.JTextField jTextFieldCodCliente;
    private javax.swing.JTextField jTextFieldCodFilme;
    private javax.swing.JTextField jTextFieldCodFilmeDevolucao;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldCodigoClienteCaixa;
    private javax.swing.JTextField jTextFieldCodigoFilmeCaixa;
    private javax.swing.JTextField jTextFieldCodigoLocacao;
    private javax.swing.JTextField jTextFieldDevolucaoCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPagou;
    private javax.swing.JTextField jTextFieldPrecoFixoCaixa;
    private javax.swing.JTextField jTextFieldQtdFilmeCaixa;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    public void horaStart() {

        Date data = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        // data do jFormattedDataLocacao do Caixa
        jFormattedDataLocacao.setText(formato.format(data));

        th = new Thread(() -> {
            while (this.executaHora == true) { //roda indefinidamente
                Date date = Calendar.getInstance().getTime(); //pega a hora do sistema
                DateFormat formatter = new SimpleDateFormat("HH:mm:ss");
                String hora = formato.format(data) + " - " + formatter.format(date);
                jLabelHora.setText(hora);
                try {
                    Thread.sleep(1000); //espera 1 segundo para fazer a nova evolução
                } catch (InterruptedException ex) {
                    //é algo terrível a se fazer mas pelo jeito a API medonha do Java exige
                }
            }
        } //cria uma thread
        );
        th.start();
    }

    // método utilitário para formatar data
    private java.sql.Date formatadorData(String dataSTR) {
        java.sql.Date dataSQL = null;
        try {
            SimpleDateFormat formata = new SimpleDateFormat("dd/MM/yyyy");
            String dataRecebida = dataSTR;
            Date data = formata.parse(dataRecebida);
            dataSQL = new java.sql.Date(data.getTime());

        } catch (ParseException ex) {
            System.err.println("err: " + ex.getMessage());
        }
        return dataSQL;
    }
}
